steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'paypalwebhookhandler'
  - '--source=.'
  - '--region=us-central1'
  - '--allow-unauthenticated'
  - '--project=guided-botswana'
  id: Deploy to Cloud Run
options:
  logging: GCS_ONLY
logsBucket: gs://guided-botswana-cloudbuild-logs